---
name: terraform-enterprise
services:
  tfe:
    image: images.releases.hashicorp.com/hashicorp/terraform-enterprise:v202402-1
    security_opt:
      - 'seccomp:unconfined'
    environment:
      TFE_LICENSE: "02MV4UU43BK5HGYYTOJZWFQMTMNNEWU33JLFLVM3CPKRITETL2IV2FSV2VGJMVGMBSJV5E43KMKRSGUT2XLF2E6RDHGVNGUVJRJ5DVU2COKRATKSLJO5UVSM2WPJSEOOLULJMEUZTBK5IWST3JJJWE6VCKNNGUITJSLJJTC2KNNJWGYTCUIEZFSVCNORMWUSTMJ5JTA52ZPJATITTKNBUFUV2ONFGUIRLJJRBUU4DCNZHDAWKXPBZVSWCSOBRDENLGMFLVC2KPNFEXCSLJO5UWCWCOPJSFOVTGMRDWY5C2KNETMSLKJF3U22SRORGUISLUJVCFUVKNKRITMTSUKE3E2RCROVHFIY32J5KEC52NNJMTIV3JJFZUS3SOGBMVQSRQLAZVE4DCK5KWST3JJF4U2RCJGBGFIQLZJRKECMSWIRAXOT3KIF3U62SBO5LWSSLTJFWVMNDDI5WHSWKYKJYGEMRVMZSEO3DULJJUSNSJNJEXOTLKKV2E2RCNORGUIZCVJVCECNSNIRATMTKEIJQUS2LXNFSEOVTZMJLWY5KZLBJHAYRSGVTGIR3MORNFGSJWJFVES52NNJKXITKEJV2E2RDEKVGUIQJWJVCECNSNIRBGCSLJO5UWGSCKOZNEQVTKMRBUSNSJNZJGYY3OJJUFU3JZPFRFGSLTJFWVU42ZK5SHUSLKOA3WMWBQHUXESQTTGN4WS4KNJNSWI3CWLJKTAZD2N5MXKRSQOFIXO23VJBLVOU2MKRUHEOCMKBASWQ2BMNYUSWBQIVWDMK2CHFFXCOKLJJRXO3DHKVTXOQ2XJ5EEW32EMN3C6NDNGZYHQ53QMNBFUMLEIFVWGYJUMRLDAMZTHBIHO3KWNRQXMSSQGRYEU6CJJE4UINSVIZGFKYKWKBVGWV2KORRUINTQMFWDM32PMZDW4SZSPJIEWSSSNVDUQVRTMVNHO4KGMUVW6N3LF5ZSWQKUJZUFAWTHKMXUWVSZM4XUWK3MI5IHOTBXNJBHQSJXI5HWC2ZWKVQWSYKIN5SWWMCSKRXTOMSEKE6T2"
      TFE_HOSTNAME: "terraform.local"
      TFE_ENCRYPTION_PASSWORD: "abcdefghijklmnopqrstuvwxyz123456"
      TFE_OPERATIONAL_MODE: "disk"
      TFE_HTTP_PORT: 8080
      TFE_HTTPS_PORT: 8443
      TFE_DISK_CACHE_VOLUME_NAME: "demoland_terraform-enterprise-cache"
      TFE_TLS_CERT_FILE: "/etc/ssl/private/terraform-enterprise/cert.pem"
      TFE_TLS_KEY_FILE: "/etc/ssl/private/terraform-enterprise/key.pem"
      TFE_TLS_CA_BUNDLE_FILE: "/etc/ssl/private/terraform-enterprise/bundle.pem"
#      TFE_IACT_SUBNETS: "<IACT subnet, eg. 10.0.0.0/8,192.168.0.0/24>"
    cap_add:
      - IPC_LOCK
    read_only: true
    tmpfs:
      - /tmp:mode=01777
      - /run
      - /var/log/terraform-enterprise
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /run/docker.sock
      - type: bind
        source: /Users/dfedick/sw/terraform-fdo/certs
        target: /etc/ssl/private/terraform-enterprise
      - type: bind
        source: /Users/dfedick/sw/terraform-fdo/lib
        target: /var/lib/terraform-enterprise
      - type: volume
        source: terraform-enterprise-cache
        target: /var/cache/tfe-task-worker/terraform
volumes:
  terraform-enterprise-cache:
